version: 1.5.{build}
image: Visual Studio 2019
install:
build_script:
- ps: .\build.ps1
artifacts:
- path: bin
  name: Shibari
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true